# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e2279b765ac740c6fb6a5798ec3ebe15"
name = "b-sections"
handle = "b-sections"
application_url = "https://cb-debug-improvement-genetics.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "yesssgirl.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,read_themes,write_themes"

[auth]
redirect_urls = [
  "https://cb-debug-improvement-genetics.trycloudflare.com/auth/callback",
  "https://cb-debug-improvement-genetics.trycloudflare.com/auth/shopify/callback",
  "https://cb-debug-improvement-genetics.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
